### ISSUE TITLE
Preview in browser

### ISSUE THREAD

**Issue by Corcules** [bdkjones/CodeKitNova#2]
hello, 

"Preview in browser" command go to url "http://127.0.0.1:5757".
In CodeKit's Project Settings, if i have a specified "External Server Adress" as "http://mydomain.local", it should be used instead...

**Comment by bdkjones** [comment]
Nope. You still want to load CodeKit's Preview address. That is the only way you get BrowserSyncing and live reloads. If you go to the external server address directly, those features won't work.

CodeKit's server will reverse-proxy the external server.

**Comment by Corcules** [comment]
Ok i misspoke. But :
Command "Preview in browser" from Nova go to "http://127.0.0.1:5757".
"Preview in browser" from Codekit go to "http://maxibob.home:5757".

it's not very important but it's should be the same...

**Comment by bdkjones** [comment]
Ah. The 127.0.0.1 address is more reliable and usually a bit faster. It’s limited to the Mac where CodeKit is running. But since Nova is also on that Mac, it makes sense to use it in that case.
